language: python
python:
  - "2.7"
  # - "2.6"

install:
  - "pip install pycurl"
  - "sudo useradd shinken"
  - "pip install -r requirements.txt"
  - "pip install coveralls"

script:
  - cd test
  - pip freeze
  - nosetests -xv --process-restartworker --processes=1 --process-timeout=300 --with-coverage --cover-package=module test*.py
  - coverage combine
  - coverage report -m
  - cd ..

after_success:
  # to get coverage data with relative paths and not absolute we have to
  # execute coveralls from the base directory of the project,
  # so we need to move the .coverage file here :
  mv test/.coverage . && coveralls --rcfile=test/.coveragerc -v
